symbol = input("Enter the symbol of the element: ")

all_elements = {
    "H":{
        "name": "Hydrogen",
        "symbol": "H",
        "atomic_number": 1,
        "atomic_mass": 1.008,
        "boiling_point": 20.271,
        "melting_point": 13.99,
        "density": 0.00008988,
    },
    "He":{
        "name": "Helium",
        "symbol": "He",
        "atomic_number": 2,
        "atomic_mass": 4.0026,
        "boiling_point": 4.222,
        "melting_point": 0.95,
        "density": 0.0001785,   
    },
    "Li":{
        "name": "Lithium",
        "symbol": "Li",
        "atomic_number": 3,
        "atomic_mass": 6.941,
        "boiling_point": 1342,
        "melting_point": 180.54,
        "density": 0.534,
    },
    "Be":{
        "name": "Beryllium",
        "symbol": "Be",
        "atomic_number": 4,
        "atomic_mass": 9.0122,
        "boiling_point": 2742,
        "melting_point": 1287,
        "density": 1.85,    
    },
    "B":{
        "name": "Boron",
        "symbol": "B",
        "atomic_number": 5,
        "atomic_mass": 10.811,
        "boiling_point": 2573,
        "melting_point": 2349,
        "density": 2.34,
    },
    "C":{
        "name": "Carbon",
        "symbol": "C",
        "atomic_number": 6,
        "atomic_mass": 12.011,
        "boiling_point": 3550,
        "melting_point": 3550,
        "density": 2.267,
    },
    "N":{
        "name": "Nitrogen",
        "symbol": "N",
        "atomic_number": 7,
        "atomic_mass": 14.007,
        "boiling_point": 77.36,
        "melting_point": 63.15,
        "density": 0.0012506,
    },
    "O":{
        "name": "Oxygen",
        "symbol": "O",
        "atomic_number": 8,
        "atomic_mass": 15.999,
        "boiling_point": 90.188,
        "melting_point": 54.36,
        "density": 0.001429,
    },
    "F":{
        "name": "Fluorine",
        "symbol": "F",
        "atomic_number": 9,
        "atomic_mass": 18.998,
        "boiling_point": 85.03,
        "melting_point": 53.53,
        "density": 0.001696,
    },
    "Ne":{
        "name": "Neon",
        "symbol": "Ne",
        "atomic_number": 10,
        "atomic_mass": 20.180,
        "boiling_point": 27.07,
        "melting_point": 24.56,
        "density": 0.000900,
    },
    "Na":{
        "name": "Sodium",
        "symbol": "Na",
        "atomic_number": 11,
        "atomic_mass": 22.990,
        "boiling_point": 882.9,
        "melting_point": 370.9,
        "density": 0.971,
    },
    "K":{
        "name": "Potassium",
        "symbol": "K",
        "atomic_number": 19,
        "atomic_mass": 39.102,
        "boiling_point": 774,
        "melting_point": 336.53,
        "density": 0.862,
    },
    "Ca":{
        "name": "Calcium",
        "symbol": "Ca",
        "atomic_number": 20,
        "atomic_mass": 40.078,
        "boiling_point": 1484,
        "melting_point": 799,
        "density": 1.55,  
    },
    "Sc":{
        "name": "Scandium",
        "symbol": "Sc",
        "atomic_number": 21,
        "atomic_mass": 44.956,
        "boiling_point": 2835,
        "melting_point": 1811,
        "density": 2.985,
    },
    "Ti":{
        "name": "Titanium",
        "symbol": "Ti",
        "atomic_number": 22,
        "atomic_mass": 47.867,
        "boiling_point": 3287,
        "melting_point": 1941,
        "density": 4.506,
    },
    "V":{
        "name": "Vanadium",
        "symbol": "V",
        "atomic_number": 23,
        "atomic_mass": 50.942,
        "boiling_point": 3680,
        "melting_point": 2183,
        "density": 6.11,
    },
    "Cr":{
        "name": "Chromium",
        "symbol": "Cr",
        "atomic_number": 24,
        "atomic_mass": 51.996,
        "boiling_point": 2945,
        "melting_point": 2180,
        "density": 7.19,
    },
    "Mn":{
        "name": "Manganese",
        "symbol": "Mn",
        "atomic_number": 25,
        "atomic_mass": 54.938,
        "boiling_point": 2061,
        "melting_point": 1519,
        "density": 7.21,
    },
    "Fe":{
        "name": "Iron",
        "symbol": "Fe",
        "atomic_number": 26,
        "atomic_mass": 55.845,
        "boiling_point": 3134,
        "melting_point": 1811,
        "density": 7.874,
    },
    "Co":{
        "name": "Cobalt",
        "symbol": "Co",
        "atomic_number": 27,
        "atomic_mass": 58.933,
        "boiling_point": 3200,
        "melting_point": 1768,
        "density": 8.90,
    },
    "Ni":{
        "name": "Nickel",
        "symbol": "Ni",
        "atomic_number": 28,
        "atomic_mass": 58.693,
        "boiling_point": 3186,
        "melting_point": 1728,
        "density": 8.908,
    },
    "Cu":{
        "name": "Copper",
        "symbol": "Cu",
        "atomic_number": 29,
        "atomic_mass": 63.546,
        "boiling_point": 2567,
        "melting_point": 1357.77,
        "density": 8.92,
    },
    "Zn":{
        "name": "Zinc",
        "symbol": "Zn",
        "atomic_number": 30,
        "atomic_mass": 65.38,
        "boiling_point": 907,
        "melting_point": 692.68,
        "density": 7.13,
    },
    "Ga":{
        "name": "Gallium",
        "symbol": "Ga",
        "atomic_number": 31,
        "atomic_mass": 69.723,
        "boiling_point": 2477,
        "melting_point": 302.91,
        "density": 5.904,
    },
    "Ge":{
        "name": "Germanium",
        "symbol": "Ge",
        "atomic_number": 32,
        "atomic_mass": 72.64,
        "boiling_point": 2830,
        "melting_point": 1211.4,
        "density": 5.323,
    },
    "As":{
        "name": "Arsenic",
        "symbol": "As",
        "atomic_number": 33,
        "atomic_mass": 74.9216,
        "boiling_point": 887,
        "melting_point": 1090,
        "density": 5.727,
    },
    "Se":{
        "name": "Selenium",
        "symbol": "Se",
        "atomic_number": 34,
        "atomic_mass": 78.96,
        "boiling_point": 958,
        "melting_point": 494,
        "density": 4.809,
    },
    "Br":{
        "name": "Bromine",
        "symbol": "Br",
        "atomic_number": 35,
        "atomic_mass": 79.904,
        "boiling_point": 58.80,
        "melting_point": 265.83,
        "density": 3.10,
    },
    "Kr":{
        "name": "Krypton",
        "symbol": "Kr",
        "atomic_number": 36,
        "atomic_mass": 83.80,
        "boiling_point": 119.93,
        "melting_point": 115.79,
        "density": 0.003749, 
    },
    "Rb":{
        "name": "Rubidium",
        "symbol": "Rb",
        "atomic_number": 37,
        "atomic_mass": 85.4678,
        "boiling_point": 312.46,
        "melting_point": 312.46,
        "density": 1.53,
    },
    "Sr":{
        "name": "Strontium",
        "symbol": "Sr",
        "atomic_number": 38,
        "atomic_mass": 87.62,
        "boiling_point": 1655,
        "melting_point": 1042,
        "density": 2.54,
    },
    "Y":{
        "name": "Yttrium",
        "symbol": "Y",
        "atomic_number": 39,
        "atomic_mass": 88.9058,
        "boiling_point": 3618,
        "melting_point": 1799,
        "density": 4.47,
    },
    "Zr":{
        "name": "Zirconium",
        "symbol": "Zr",
        "atomic_number": 40,
        "atomic_mass": 91.224,
        "boiling_point": 4682,
        "melting_point": 2128,
        "density": 6.52,
    },
    "Nb":{
        "name": "Niobium",
        "symbol": "Nb",
        "atomic_number": 41,
        "atomic_mass": 92.90638,
        "boiling_point": 5017,
        "melting_point": 2750,
        "density": 8.57,
    },
    "Mo":{
        "name": "Molybdenum",
        "symbol": "Mo",
        "atomic_number": 42,
        "atomic_mass": 95.94,
        "boiling_point": 4639,
        "melting_point": 2896,
        "density": 10.22,
    },
    "Tc":{
        "name": "Technetium",
        "symbol": "Tc",
        "atomic_number": 43,
        "atomic_mass": 98,
        "boiling_point": 4538,
        "melting_point": 2430,
        "density": 11.5,
    },
    "Ru":{
        "name": "Ruthenium",
        "symbol": "Ru",
        "atomic_number": 44,
        "atomic_mass": 101.07,
        "boiling_point": 4423,
        "melting_point": 2607,
        "density": 12.41,
    },
    "Rh":{
        "name": "Rhodium",
        "symbol": "Rh",
        "atomic_number": 45,
        "atomic_mass": 102.9055,
        "boiling_point": 3968,
        "melting_point": 2237,
        "density": 12.41,   
    },
    "Pd":{
        "name": "Palladium",
        "symbol": "Pd",
        "atomic_number": 46,
        "atomic_mass": 106.42,
        "boiling_point": 3236,
        "melting_point": 2041.15,
        "density": 12.02,
    },
    "Ag":{
        "name": "Silver",
        "symbol": "Ag",
        "atomic_number": 47,
        "atomic_mass": 107.8682,
        "boiling_point": 2210,
        "melting_point": 1234.93,
        "density": 10.49,
    },
    "Cd":{
        "name": "Cadmium",
        "symbol": "Cd",
        "atomic_number": 48,
        "atomic_mass": 112.411,
        "boiling_point": 1040,
        "melting_point": 594.22,
        "density": 8.69,
    },
    "In":{
        "name": "Indium",
        "symbol": "In",
        "atomic_number": 49,
        "atomic_mass": 114.818,
        "boiling_point": 2345,
        "melting_point": 429.748,
        "density": 7.31,
    },
    "Sn":{
        "name": "Tin",
        "symbol": "Sn",
        "atomic_number": 50,
        "atomic_mass": 118.710,
        "boiling_point": 2875,
        "melting_point": 505.08,
        "density": 7.287,
    },  
    "Sb":{
        "name": "Antimony",
        "symbol": "Sb",
        "atomic_number": 51,
        "atomic_mass": 121.760,
        "boiling_point": 1860,
        "melting_point": 903.78,
        "density": 6.685,
    },
    "Te":{
        "name": "Tellurium",
        "symbol": "Te",
        "atomic_number": 52,
        "atomic_mass": 127.60,
        "boiling_point": 1261,
        "melting_point": 722.66,
        "density": 6.232,
    },
    "I":{
        "name": "Iodine",
        "symbol": "I",
        "atomic_number": 53,
        "atomic_mass": 126.90447,
        "boiling_point": 457.56,
        "melting_point": 386.85,
        "density": 4.93,
    },
    "Xe":{
        "name": "Xenon",
        "symbol": "Xe",
        "atomic_number": 54,
        "atomic_mass": 131.293,
        "boiling_point": 165.03,
        "melting_point": 161.4,
        "density": 0.005887, 
    },
    "Cs":{
        "name": "Cesium",
        "symbol": "Cs",
        "atomic_number": 55,
        "atomic_mass": 132.9054519,
        "boiling_point": 944,
        "melting_point": 301.59,
        "density": 1.873,
    },
    "Ba":{
        "name": "Barium",
        "symbol": "Ba",
        "atomic_number": 56,
        "atomic_mass": 137.327,
        "boiling_point": 2170,
        "melting_point": 1000,
        "density": 3.51,
    },
    "La":{
        "name": "Lanthanum",
        "symbol": "La",
        "atomic_number": 57,
        "atomic_mass": 138.90547,
        "boiling_point": 3737,
        "melting_point": 1193,
        "density": 6.162,
    },
    "Ce":{
        "name": "Cerium",
        "symbol": "Ce",
        "atomic_number": 58,
        "atomic_mass": 140.116,
        "boiling_point": 3716,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Pr":{
        "name": "Praseodymium",
        "symbol": "Pr",
        "atomic_number": 59,
        "atomic_mass": 140.90765,
        "boiling_point": 3793,
        "melting_point": 1208,
        "density": 6.77,
    },
    "Nd":{
        "name": "Neodymium",
        "symbol": "Nd",
        "atomic_number": 60,
        "atomic_mass": 144.242,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77, 
    },
    "Pm":{
        "name": "Promethium",
        "symbol": "Pm",
        "atomic_number": 61,
        "atomic_mass": 145,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Sm":{
        "name": "Samarium",
        "symbol": "Sm",
        "atomic_number": 62,
        "atomic_mass": 150.36,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Eu":{
        "name": "Europium",
        "symbol": "Eu",
        "atomic_number": 63,
        "atomic_mass": 151.964,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Gd":{
        "name": "Gadolinium",
        "symbol": "Gd",
        "atomic_number": 64,
        "atomic_mass": 157.25,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Tb":{
        "name": "Terbium",
        "symbol": "Tb",
        "atomic_number": 65,
        "atomic_mass": 158.92535,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77, 
    },
    "Dy":{
        "name": "Dysprosium",
        "symbol": "Dy",
        "atomic_number": 66,
        "atomic_mass": 162.50,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Ho":{
        "name": "Holmium",
        "symbol": "Ho",
        "atomic_number": 67,
        "atomic_mass": 164.93032,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,  
    },
    "Er":{
        "name": "Erbium",
        "symbol": "Er",
        "atomic_number": 68,
        "atomic_mass": 167.259,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Tm":{
        "name": "Thulium",
        "symbol": "Tm",
        "atomic_number": 69,
        "atomic_mass": 168.93421,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Yb":{
        "name": "Ytterbium",
        "symbol": "Yb",
        "atomic_number": 70,
        "atomic_mass": 173.04,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Lu":{
        "name": "Lutetium",
        "symbol": "Lu",
        "atomic_number": 71,
        "atomic_mass": 174.967,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Hf":{
        "name": "Hafnium",
        "symbol": "Hf",
        "atomic_number": 72,
        "atomic_mass": 178.49,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Ta":{
        "name": "Tantalum",
        "symbol": "Ta",
        "atomic_number": 73,
        "atomic_mass": 180.94788,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77, 
    },
    "W":{
        "name": "Tungsten",
        "symbol": "W",
        "atomic_number": 74,
        "atomic_mass": 183.84,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Re":{
        "name": "Rhenium",
        "symbol": "Re",
        "atomic_number": 75,
        "atomic_mass": 186.207,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Os":{
        "name": "Osmium",
        "symbol": "Os",
        "atomic_number": 76,
        "atomic_mass": 190.23,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Ir":{
        "name": "Iridium",
        "symbol": "Ir",
        "atomic_number": 77,
        "atomic_mass": 192.217,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Pt":{
        "name": "Platinum",
        "symbol": "Pt",
        "atomic_number": 78,
        "atomic_mass": 195.084,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77, 
    },
    "Au":{
        "name": "Gold",
        "symbol": "Au",
        "atomic_number": 79,
        "atomic_mass": 196.966569,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Hg":{
        "name": "Mercury",
        "symbol": "Hg",
        "atomic_number": 80,
        "atomic_mass": 200.59,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Tl":{
        "name": "Thallium",
        "symbol": "Tl",
        "atomic_number": 81,
        "atomic_mass": 204.3833,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Pb":{
        "name": "Lead",
        "symbol": "Pb",
        "atomic_number": 82,
        "atomic_mass": 207.2,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Bi":{
        "name": "Bismuth",
        "symbol": "Bi",
        "atomic_number": 83,
        "atomic_mass": 208.9804,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77, 
    },
    "Po":{
        "name": "Polonium",
        "symbol": "Po",
        "atomic_number": 84,
        "atomic_mass": 209,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "At":{
        "name": "Astatine",
        "symbol": "At",
        "atomic_number": 85,
        "atomic_mass": 210,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Rn":{
        "name": "Radon",
        "symbol": "Rn",
        "atomic_number": 86,
        "atomic_mass": 222,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Fr":{
        "name": "Francium",
        "symbol": "Fr",
        "atomic_number": 87,
        "atomic_mass": 223,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Ra":{
        "name": "Radium",
        "symbol": "Ra",
        "atomic_number": 88,
        "atomic_mass": 226,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Ac":{
        "name": "Actinium",
        "symbol": "Ac",
        "atomic_number": 89,
        "atomic_mass": 227,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,   
    },
    "Th":{
        "name": "Thorium",
        "symbol": "Th",
        "atomic_number": 90,
        "atomic_mass": 232.038,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Pa":{
        "name": "Protactinium",
        "symbol": "Pa",
        "atomic_number": 91,
        "atomic_mass": 231.03588,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "U":{
        "name": "Uranium",
        "symbol": "U",
        "atomic_number": 92,
        "atomic_mass": 238.02891,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Np":{
        "name": "Neptunium",
        "symbol": "Np",
        "atomic_number": 93,
        "atomic_mass": 237.0482,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Pu":{
        "name": "Plutonium",
        "symbol": "Pu",
        "atomic_number": 94,
        "atomic_mass": 244,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Am":{
        "name": "Americium",
        "symbol": "Am",
        "atomic_number": 95,
        "atomic_mass": 243,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Cm":{
        "name": "Curium",
        "symbol": "Cm",
        "atomic_number": 96,
        "atomic_mass": 247,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,    
    },
    "Bk":{
        "name": "Berkelium",
        "symbol": "Bk",
        "atomic_number": 97,
        "atomic_mass": 247,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Cf":{
        "name": "Californium",
        "symbol": "Cf", 
        "atomic_number": 98,
        "atomic_mass": 249,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Es":{
        "name": "Einsteinium",
        "symbol": "Es",
        "atomic_number": 99,
        "atomic_mass": 251,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Fm":{
        "name": "Fermium",
        "symbol": "Fm",
        "atomic_number": 100,
        "atomic_mass": 252,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Md":{
        "name": "Mendelevium",
        "symbol": "Md",
        "atomic_number": 101,
        "atomic_mass": 258,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "No":{
        "name": "Nobelium",
        "symbol": "No", 
        "atomic_number": 102,
        "atomic_mass": 259,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,    
    },
    "Lr":{
        "name": "Lawrencium",
        "symbol": "Lr",
        "atomic_number": 103,
        "atomic_mass": 262,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,        
    },
    "Rf":{
        "name": "Rutherfordium",
        "symbol": "Rf",
        "atomic_number": 104,
        "atomic_mass": 265,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Db":{
        "name": "Dubnium",
        "symbol": "Db",
        "atomic_number": 105,
        "atomic_mass": 268,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Sg":{
        "name": "Seaborgium",
        "symbol": "Sg", 
        "atomic_number": 106,
        "atomic_mass": 271,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },  
    "Bh":{
        "name": "Bohrium",
        "symbol": "Bh",
        "atomic_number": 107,
        "atomic_mass": 272,
        "boiling_point": 3793,  
        "melting_point": 1295,
        "density": 6.77,
    },
    "Hs":{
        "name": "Hassium",
        "symbol": "Hs", 
        "atomic_number": 108,
        "atomic_mass": 270,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },  
    "Mt":{
        "name": "Meitnerium",
        "symbol": "Mt",
        "atomic_number": 109,
        "atomic_mass": 276,
        "boiling_point": 3793,  
        "melting_point": 1295,
        "density": 6.77,
    },
    "Ds":{
        "name": "Darmstadtium",
        "symbol": "Ds", 
        "atomic_number": 110,
        "atomic_mass": 281,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,    
    },
    "Rg":{
        "name": "Roentgenium",
        "symbol": "Rg",
        "atomic_number": 111,
        "atomic_mass": 281,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
    "Cn":{
        "name": "Copernicium",
        "symbol": "Cn", 
        "atomic_number": 112,
        "atomic_mass": 285,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },  
    "Nh":{
        "name": "Nihonium",
        "symbol": "Nh", 
        "atomic_number": 113,
        "atomic_mass": 286,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },  
    "Fl":{
        "name": "Flerovium",
        "symbol": "Fl", 
        "atomic_number": 114,
        "atomic_mass": 289,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },  
    "Mc":{
        "name": "Moscovium",
        "symbol": "Mc", 
        "atomic_number": 115,
        "atomic_mass": 289,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },  
    "Lv":{
        "name": "Livermorium",
        "symbol": "Lv", 
        "atomic_number": 116,
        "atomic_mass": 293,
        "boiling_point": 3793,  
        "melting_point": 1295,
        "density": 6.77,
    },
    "Ts":{
        "name": "Tennessine",
        "symbol": "Ts",     
        "atomic_number": 117,
        "atomic_mass": 294,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },  
    "Og":{
        "name": "Oganesson",
        "symbol": "Og", 
        "atomic_number": 118,
        "atomic_mass": 294,
        "boiling_point": 3793,
        "melting_point": 1295,
        "density": 6.77,
    },
}
print(all_elements[symbol])







#